FROM httpd

LABEL \ 
description="This is a base image for tests in Kubernetes clusters" \
author="Pavel Dumenko" \
email="pashadumenko35738@gmail.com"

COPY ./assets/* /usr/local/apache2/htdocs/

EXPOSE 80